### ISSUE TITLE
文字列連結周りのバグ修正

### ISSUE THREAD

**Issue by tabata0330** [ToyamaLab/NewSSQL#2]
**担当 : tabata**
○バグ内容   
- 集約関数との連結ができない
→DCでエラーが出る
- SQL関数との連結ができない
→パーサーで弾かれる

○修正案1
- パーサー
    SQL関数を含む文字列の連結を許す
    その上で連結する属性同士はバラバラに扱う(これはASについても同じ)
- DC
    SQL作成の時は連結文字列は省く。ASは左辺と右辺をASで連結して問い合わせる
    データ取得後集計が終わったら文字列連結を実行する。
    その後ネスティング

○修正案2

**Comment by tabata0330** [comment]
修正案1を具体化
○パーサー時点
→文字列連結の場合は
`[operand, [[join_string, [[attribute, [[table_alias, [[any_name, [m]]]], ., [column_name, [[any_name, [name]]]]]], ||, [sl, ['さん']]]]]]`	
てなってるからasの時もas_pairみたいな感じにしてあげる
		
○属性の読み取り時は分割して保持
・@codegenerator.javaのreadAttributeで(多分)属性を見つけたらそれに対応する操作をしている
→ここで属性を読み取ってmakeAttributeで格納してる
→とりあえずmakeAttributeで読むときにas_pairだったりjoin_stringだったら一つのattnoに対して複数の物を持たせるようにする。
e.g. `['マネージャーの'||m.name||'さん', [e.name||'、給料は' || e.salary]!]!` の場合
`0=['マネージャーの', 'm.name', 'さん'], 1=['e,name', '給料は', 'e.salary']`
て感じで対応づけて保持。属性とただの文字列を区別する方法(prefix的な何か)を用意した方が良い。
→おそらくAttributeItemとCodeGeneratorを拡張すれば行けそう
		
○問い合わせ時点
・SQLを作成する時は各attno毎に属性を抜き出してクエリに入れる
		
○DC時点
・集約とソーティングが終わったらattnoを元に連結を行う

**Comment by tabata0330** [comment]
詳細
○パーサー

- 文字列連結

→属性、数字、文字列、集約関数、SQL関数の連結を全て許す

- AS

→属性、集約関数、SQL関数 AS 文字列を許す
	
とりあえず許可はする様になった。そのあとの処理は適宜追加。

**Comment by tabata0330** [comment]
### 途中経過報告
修正案1だと大変面倒なことに気づいたので、新たに以下の修正案2を考えました。
#### 修正案2
○概要
HTMLC1とかと同じ発想でHTMLJOINというlayout expressionを作成。
CodeGeneratorで出力するときに連結させて出力する。
○実装
@ query.g4
join_stringというルールを無くし、join_expというルールを作成。`||`で属性を区切って保持。
@ Data Constructor
処理は従来通り。
@ Code Generator
HTMLJOINが出てきたらその子要素に当たるdata_infoを全部連結してappendする。

ざっくりとこんな感じです。詳しくはcommit 0028471375e39015b90f653ff0a68afa6ca07861を確認してください。
一応軽く動作確認してみたところ集約関数、SQL関数、文字列などの連結が可能になっています。

### このあとやること
(1)装飾子の適用について
装飾子の挙動がまだいまいちわかってないので後日追記します。
(2)デバッグ
(3)as_pairの追加
read_attributeでas_pair見つけたらmakeAttributeの際にlineとnameに分けて設定する様にする。
(4)新たに見つけたバグ
ROUND()というSQL関数を使うときに引数に`-1`を入れたらパーサーでバグが発生。後日調査します。

**Comment by tabata0330** [comment]
(1)装飾子の適用について
可能になりました。が、Connectorの階層関係に少し懸念(HTMLJOINがHTMLC0の下位にある)があるので時間ができたら確認します。

(4)新たに見つけたバグ
query.g4を少し修正したら治りました。従来のでは負の数を許可していませんでした(何か理由があったら教えてください)

**Comment by tabata0330** [comment]
新たなバグ
1. 集約関数とSQL関数の連結
2. (集約関数 or SQL関数)の四則計算

**Comment by atsu0127** [comment]
一旦閉じます
